language: python
python:
  - "3.6"

# install server dependencies
before_install:
  - "sudo apt-get -y install musl-dev g++ libgmp3-dev libmpfr-dev ca-certificates libmpc-dev"

# install dependencies
install:
  - "pip install -r test-requirements.txt"
  - "python setup.py install"

# run tests
script:
  - pytest && pytest --flake8

notifications:
    slack: openmined:vOUE1d9jSb6V7R1r6zrjRD4E
